service: sfc-ondemand-reports

custom:
  environment: ${opt:stage, 'development'}
  bucketName: "${self:custom.environment}-thisbucket"
  region: ${opt:region, 'eu-west-1'}

provider:
  name: aws
  runtime: nodejs8.10
  profile: serverless-admin
  region: ${self:custom.region}
  endpointType: REGIONAL
  stage: ${opt:stage, 'development'}
  timeout: 15
  memorySize: 128
  environment:
    LOG_LEVEL: 1      # 0-disabled; 1-errors, 2-warnings, 3-info, 4-debug, 5-trace
    SLACK_LEVEL: 1          # 0-disabled; 1-errors, 2-warnings, 3-info, 4-debug, 5-trace
  role: arn:aws:iam::#{AWS::AccountId}:role/Ssfc-dev-lambda 

package:
  individually: true
  excludeDevDependencies: false
  exclude:
    - '**/*'
    - .git/**

functions:
  snapshotReport:
    handler: snapshotReport.handler
    environment:
      SFC_API_ENDPOINT: 'https://sfcdev.cloudapps.digital/api'
      LOG_LEVEL: 3      # 0-disabled; 1-errors, 2-warnings, 3-info, 4-debug, 5-trace
      SLACK_WEBHOOK: 'SLACK_URL'
      SLACK_LEVEL: 0          # 0-disabled; 1-errors, 2-warnings, 3-info, 4-debug, 5-trace
    role: arn:aws:iam::#{AWS::AccountId}:role/sfc-dev-lambda     # note, the name of the role includes the region, but with underscores
    tags:
      application: "On-Demand Reporting"
      company: "SfC"
    package:
      include:
        - snapshotReport.js
  ingestEstablishments:
    handler: ingestEstablishments.handler
    environment:
      STREAM: 'establishments.dev'
      LOG_LEVEL: 3      # 0-disabled; 1-errors, 2-warnings, 3-info, 4-debug, 5-trace
      SLACK_WEBHOOK: 'SLACK_URL'
      SLACK_LEVEL: 0          # 0-disabled; 1-errors, 2-warnings, 3-info, 4-debug, 5-trace
      MONGO_DB_URI: ${env:MONGO_DB_URI}
    role: arn:aws:iam::#{AWS::AccountId}:role/sfc-dev-lambda     # note, the name of the role includes the region, but with underscores
    events:
      - stream:
          type: kinesis
          arn:  arn:aws:kinesis:#{AWS::Region}:#{AWS::AccountId}:stream/establishments.dev
    tags:
      application: "Pump"
      company: "SfC"
    package:
      include:
        - ingestEstablishments.js
plugins:
  - serverless-pseudo-parameters
  - serverless-plugin-include-dependencies