service: sfc-ondemand-reports

custom:
  environment: ${opt:stage, 'development'}
  bucketName: "${self:custom.environment}-thisbucket"
  region: ${opt:region, 'eu-west-1'}
  ESTABLISHMENT_KINESIS_STREAM:
    dev: arn:aws:kinesis:#{AWS::Region}:#{AWS::AccountId}:stream/establishments.dev
    staging: arn:aws:kinesis:#{AWS::Region}:#{AWS::AccountId}:stream/establishments.staging
    preprod: arn:aws:kinesis:#{AWS::Region}:#{AWS::AccountId}:stream/establishments.preprod
    prod: arn:aws:kinesis:#{AWS::Region}:#{AWS::AccountId}:stream/establishments.prod
  EMAIL_SENDER:
    dev: warren.ayling@wozitech-ltd.co.uk
    staging: warren.ayling@wozitech-ltd.co.uk
    preprod: warren.ayling@wozitech-ltd.co.uk
    prod: NMDSdevopsServiceAdm@hotmail.com
  EMAIL_RECIPIENT:
    dev: warren.ayling@wozitech-ltd.co.uk
    staging: ann.shepherd1@soprasteria.com
    preprod: warren.ayling@wozitech-ltd.co.uk
    prod: david.griffiths@skillsforcare.org.uk
  STORE:
    dev: "dev/ondemand/reporting"
    staging: "staging/ondemand/reporting"
    preprod: "preprod/ondemand/reporting"
    prod: "prod/ondemand/reporting"
  SFC_HOST:
    dev: "sfcdev.cloudapps.digital"
    staging: "sfcstaging.cloudapps.digital"
    preprod: "sfcuat.cloudapps.digital"
    prod: "asc-wds.skillsforcare.org.uk"
  DATA_VERSION:
    dev: 3
    staging: 3
    preprod: 3
    prod: 3
  S3_REPORTS_BUCKET:
    dev: sfc-reports-buckets-dev
    staging: sfc-reports-buckets-staging
    preprod: sfc-reports-buckets-preprod
    prod: sfc-reports-buckets-prod

provider:
  name: aws
  runtime: nodejs8.10
  profile: serverless-admin
  region: ${self:custom.region}
  endpointType: REGIONAL
  stage: ${opt:stage, 'development'}
  timeout: 15
  memorySize: 128
  environment:
    LOG_LEVEL: 1      # 0-disabled; 1-errors, 2-warnings, 3-info, 4-debug, 5-trace
    SLACK_LEVEL: 1          # 0-disabled; 1-errors, 2-warnings, 3-info, 4-debug, 5-trace
    STORE: "${self:custom.STORE.${self:provider.stage}}"
  role: "arn:aws:iam::#{AWS::AccountId}:role/sfc-${self:provider.stage}-lambda"

package:
  individually: true
  excludeDevDependencies: false
  exclude:
    - '**/*'
    - .git/**

functions:
  snapshotReport:
    handler: snapshotReport.handler
    memorySize: 512
    timeout: 15
    environment:
      SFC_HOST: "${self:custom.SFC_HOST.${self:provider.stage}}"
      LOG_LEVEL: 3      # 0-disabled; 1-errors, 2-warnings, 3-info, 4-debug, 5-trace
      EMAIL_SENDER: "${self:custom.EMAIL_SENDER.${self:provider.stage}}"
      EMAIL_RECIPIENT: "${self:custom.EMAIL_RECIPIENT.${self:provider.stage}}"
      DATA_VERSION: "${self:custom.DATA_VERSION.${self:provider.stage}}"
      S3_REPORTS_BUCKET: "${self:custom.S3_REPORTS_BUCKET.${self:provider.stage}}"
      SLACK_LEVEL: 3
    tags:
      application: "Reporting"
      function: "On Demand Reporting"
      company: "SfC"
    package:
      include:
        - snapshotReport.js
  establishmentsIngest:
    handler: ingestEstablishments.handler
    memorySize: 128
    timeout: 30
    environment:
      STREAM: 'establishments.dev'
      LOG_LEVEL: 3      # 0-disabled; 1-errors, 2-warnings, 3-info, 4-debug, 5-trace
      #MONGO_DB_URI: ${env:MONGO_DB_URI}
    events:
      - stream:
          type: kinesis
          arn:  "${self:custom.ESTABLISHMENT_KINESIS_STREAM.${self:provider.stage}}"
          batchSize: 100
          startingPosition: LATEST
    tags:
      application: "Pump"
      function: "On Demand Reporting"
      company: "SfC"
    package:
      include:
        - ingestEstablishments.js
  hasher:
    handler: hasher.handler
    memorySize: 128
    timeout: 3
    environment:
      HASH_SALT: 'xx'
      HASH_TARGET: 'xx'
    tags:
      application: "Trial"
      function: "Hashing"
      company: "SfC"
    events:
      - http:
          path: hasher
          method: post
          cors: true
    package:
      include:
        - hasher.js
plugins:
  - serverless-pseudo-parameters
  - serverless-plugin-include-dependencies