service: sfc-ondemand-reports

custom:
  environment: ${opt:stage, 'development'}
  bucketName: "${self:custom.environment}-thisbucket"
  region: ${opt:region, 'eu-west-1'}

provider:
  name: aws
  runtime: nodejs8.10
  profile: serverless-admin
  region: ${self:custom.region}
  endpointType: REGIONAL
  stage: ${opt:stage, 'development'}
  timeout: 15
  memorySize: 128
  environment:
    LOG_LEVEL: 1      # 0-disabled; 1-errors, 2-warnings, 3-info, 4-debug, 5-trace
    SLACK_LEVEL: 1          # 0-disabled; 1-errors, 2-warnings, 3-info, 4-debug, 5-trace
  role: arn:aws:iam::#{AWS::AccountId}:role/SfC_eu_west_1_ondemand_reporting

package:
  individually: true
  excludeDevDependencies: false
  exclude:
    - '**/*'
    - .git/**

functions:
  snppshotReport:
    handler: snapshotReport.handler
    environment:
      SFC_API_ENDPOINT: 'https://sfcdev.cloudapps.digital/api'
      LOG_LEVEL: 3      # 0-disabled; 1-errors, 2-warnings, 3-info, 4-debug, 5-trace
      SLACK_WEBHOOK: 'SLACK_URL'
      SLACK_LEVEL: 0          # 0-disabled; 1-errors, 2-warnings, 3-info, 4-debug, 5-trace
    role: arn:aws:iam::#{AWS::AccountId}:role/SfC_eu_west_1_ondemand_reporting    # note, the name of the role includes the region, but with underscores
    tags:
      application: "On-Demand Reporting"
      company: "SfC"
    package:
      include:
        - snapshotReport.js

plugins:
  - serverless-pseudo-parameters
  - serverless-plugin-include-dependencies